apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-service
data:
  application.yml: |
    demo:
      message: Spring Boot on Kubernetes!
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 15s
    management:
      endpoints:
        web:
          exposure:
            include: health,prometheus